window.CRM_LEADS = [
  {
    "id": "beautyspace_riga",
    "businessName": "Beauty Space Riga",
    "categoryPrimary": "beauty_studio",
    "categorySecondary": "hair",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "beautyspace_riga",
    "instagramUrl": "https://www.instagram.com/beautyspace_riga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37126344032",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "budget",
    "audienceSignal": "local_consumer",
    "languageSignal": "mixed",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business phone visible in snippet",
    "fitScore": 80,
    "confidenceScore": "high",
    "qaStatus": "approved"
  },
  {
    "id": "fiesta.skincare",
    "businessName": "Fiesta Skincare",
    "categoryPrimary": "beauty_studio",
    "categorySecondary": "skincare",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "fiesta.skincare",
    "instagramUrl": "https://www.instagram.com/fiesta.skincare/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Beauty/skincare specialist",
    "fitScore": 74,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "glowstudioriga",
    "businessName": "Glow Studio Riga",
    "categoryPrimary": "beauty_studio",
    "categorySecondary": "nails",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "glowstudioriga",
    "instagramUrl": "https://www.instagram.com/glowstudioriga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business profile found",
    "fitScore": 64,
    "confidenceScore": "low",
    "qaStatus": "needs_review"
  },
  {
    "id": "glow_tan_beauty_riga",
    "businessName": "Glow Tan Beauty Riga",
    "categoryPrimary": "beauty_studio",
    "categorySecondary": "tanning",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "glow_tan_beauty_riga",
    "instagramUrl": "https://www.instagram.com/glow_tan_beauty_riga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Tanning adjacent beauty fit",
    "fitScore": 70,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "jusukosmetologs",
    "businessName": "JK Klinika",
    "categoryPrimary": "beauty_studio",
    "categorySecondary": "skincare",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "jusukosmetologs",
    "instagramUrl": "https://www.instagram.com/jusukosmetologs/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37120750750",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "mid",
    "audienceSignal": "local_consumer",
    "languageSignal": "mixed",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Clinic-like profile may be slightly outside target",
    "fitScore": 66,
    "confidenceScore": "medium",
    "qaStatus": "needs_review"
  },
  {
    "id": "medspa_cosmetology",
    "businessName": "Medspa Cosmetology",
    "categoryPrimary": "beauty_studio",
    "categorySecondary": "cosmetology",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "medspa_cosmetology",
    "instagramUrl": "https://www.instagram.com/medspa_cosmetology/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Beauty/cosmetology fit",
    "fitScore": 73,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "nowabeauty.lv",
    "businessName": "Nowa Beauty",
    "categoryPrimary": "beauty_studio",
    "categorySecondary": "nails",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "nowabeauty.lv",
    "instagramUrl": "https://www.instagram.com/nowabeauty.lv/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "browser",
    "leadSourceSecondary": "google_search",
    "complianceNotes": "Old Town Riga beauty account with online booking",
    "fitScore": 78,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "terezaswaxing",
    "businessName": "Terezas Waxing",
    "categoryPrimary": "beauty_studio",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "terezaswaxing",
    "instagramUrl": "https://www.instagram.com/terezaswaxing/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "explicit",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Strong beauty studio fit",
    "fitScore": 78,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "gode.riga",
    "businessName": "GODE Riga",
    "categoryPrimary": "boutique_fashion",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "gode.riga",
    "instagramUrl": "https://www.instagram.com/gode.riga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "fashion",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Multi-brand fashion store in Riga",
    "fitScore": 66,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "plaza_fashionstore",
    "businessName": "Plaza Fashion Store",
    "categoryPrimary": "boutique_fashion",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "plaza_fashionstore",
    "instagramUrl": "https://www.instagram.com/plaza_fashionstore/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37126572504",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "premium",
    "audienceSignal": "fashion",
    "languageSignal": "en",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Store profile found with public inquiry number",
    "fitScore": 65,
    "confidenceScore": "medium",
    "qaStatus": "needs_review"
  },
  {
    "id": "podium_fashionstore_riga",
    "businessName": "Podium Fashionstore Riga",
    "categoryPrimary": "boutique_fashion",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "podium_fashionstore_riga",
    "instagramUrl": "https://www.instagram.com/podium_fashionstore_riga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37126606060",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "mid",
    "audienceSignal": "fashion",
    "languageSignal": "mixed",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business phone visible in snippet",
    "fitScore": 70,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "rigaworld",
    "businessName": "Riga Fashion House",
    "categoryPrimary": "boutique_fashion",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "rigaworld",
    "instagramUrl": "https://www.instagram.com/rigaworld/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "fashion",
    "audienceSignal": "en",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "DM for inquiries in snippet",
    "fitScore": 68,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "showroomchoco",
    "businessName": "Showroom Choco",
    "categoryPrimary": "boutique_fashion",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "showroomchoco",
    "instagramUrl": "https://www.instagram.com/showroomchoco/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37120040469",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "mid",
    "audienceSignal": "fashion",
    "languageSignal": "unknown",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business phone visible in snippet",
    "fitScore": 76,
    "confidenceScore": "high",
    "qaStatus": "approved"
  },
  {
    "id": "theline.lv",
    "businessName": "The Line LV",
    "categoryPrimary": "boutique_fashion",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "theline.lv",
    "instagramUrl": "https://www.instagram.com/theline.lv/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "premium",
    "priceLevelSignal": "fashion",
    "audienceSignal": "en",
    "languageSignal": "",
    "lastActivityDatePublic": "active",
    "activeStatus": "web_search",
    "leadSourcePrimary": "instagram",
    "leadSourceSecondary": "More polished boutique",
    "complianceNotes": "lower microbusiness confidence",
    "fitScore": 60,
    "confidenceScore": "low",
    "qaStatus": "needs_review"
  },
  {
    "id": "browstudio_riga",
    "businessName": "Browstudio Riga",
    "categoryPrimary": "brows",
    "categorySecondary": "lashes",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "browstudio_riga",
    "instagramUrl": "https://www.instagram.com/browstudio_riga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Direct brow/lash/makeup fit",
    "fitScore": 77,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "ssbrows_riga",
    "businessName": "SS Brows Riga",
    "categoryPrimary": "brows",
    "categorySecondary": "makeup",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "ssbrows_riga",
    "instagramUrl": "https://www.instagram.com/ssbrows_riga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37128763855",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "solo",
    "priceLevelSignal": "mid",
    "audienceSignal": "local_consumer",
    "languageSignal": "mixed",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business phone visible in snippet",
    "fitScore": 86,
    "confidenceScore": "high",
    "qaStatus": "approved"
  },
  {
    "id": "beyou_vecriga",
    "businessName": "BeYou Vecriga",
    "categoryPrimary": "hair",
    "categorySecondary": "nails",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "beyou_vecriga",
    "instagramUrl": "https://www.instagram.com/beyou_vecriga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Category appears mixed hair/nails",
    "fitScore": 68,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "hairriga_saloni",
    "businessName": "Hairriga Saloni",
    "categoryPrimary": "hair",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "hairriga_saloni",
    "instagramUrl": "https://www.instagram.com/hairriga_saloni/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "May be larger than ideal microbusiness",
    "fitScore": 63,
    "confidenceScore": "medium",
    "qaStatus": "needs_review"
  },
  {
    "id": "karpovahair",
    "businessName": "Karpova Hair",
    "categoryPrimary": "hair",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "karpovahair",
    "instagramUrl": "https://www.instagram.com/karpovahair/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "explicit",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Personal-brand stylist account",
    "fitScore": 78,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "kitchenhairlab",
    "businessName": "KitchenHairLab",
    "categoryPrimary": "hair",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "kitchenhairlab",
    "instagramUrl": "https://www.instagram.com/kitchenhairlab/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37125622888",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "mid",
    "audienceSignal": "local_consumer",
    "languageSignal": "unknown",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Good hair fit but owner signal weaker",
    "fitScore": 74,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "natalia_kuznetsova_hairart",
    "businessName": "Natalia Kuznetsova Hair Art",
    "categoryPrimary": "hair",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "natalia_kuznetsova_hairart",
    "instagramUrl": "https://www.instagram.com/natalia_kuznetsova_hairart/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "explicit",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Personal-brand stylist account",
    "fitScore": 76,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "pavlovskahairdresser",
    "businessName": "Pavlovska Hairdresser",
    "categoryPrimary": "hair",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "pavlovskahairdresser",
    "instagramUrl": "https://www.instagram.com/pavlovskahairdresser/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "explicit",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Personal-brand stylist account",
    "fitScore": 76,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "style_by_om",
    "businessName": "Style by OM",
    "categoryPrimary": "hair",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "style_by_om",
    "instagramUrl": "https://www.instagram.com/style_by_om/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "explicit",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Personal-brand stylist account",
    "fitScore": 75,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "valerijahair",
    "businessName": "Valerija Hair",
    "categoryPrimary": "hair",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "valerijahair",
    "instagramUrl": "https://www.instagram.com/valerijahair/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "explicit",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Personal-brand stylist account",
    "fitScore": 75,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "alishalashes_riga",
    "businessName": "Alisha Lashes Riga",
    "categoryPrimary": "lashes",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "alishalashes_riga",
    "instagramUrl": "https://www.instagram.com/alishalashes_riga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Personal-brand style lash account",
    "fitScore": 74,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "danii.lashstudio",
    "businessName": "Danii Lashstudio",
    "categoryPrimary": "lashes",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "danii.lashstudio",
    "instagramUrl": "https://www.instagram.com/danii.lashstudio/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Personal-brand style lash studio",
    "fitScore": 75,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "evija_lashes_riga",
    "businessName": "Evija Lashes Riga",
    "categoryPrimary": "lashes",
    "categorySecondary": "brows",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "evija_lashes_riga",
    "instagramUrl": "https://www.instagram.com/evija_lashes_riga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37129950044",
    "publicEmail": "",
    "ownerNamePublic": "Evija",
    "femaleOwnerSignal": "explicit",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "solo",
    "priceLevelSignal": "mid",
    "audienceSignal": "local_consumer",
    "languageSignal": "mixed",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public phone and named owner signal in snippet",
    "fitScore": 88,
    "confidenceScore": "high",
    "qaStatus": "approved"
  },
  {
    "id": "lashbrows.studio",
    "businessName": "Lashbrows Studio",
    "categoryPrimary": "lashes",
    "categorySecondary": "brows",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "lashbrows.studio",
    "instagramUrl": "https://www.instagram.com/lashbrows.studio/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Direct lash/brow studio fit",
    "fitScore": 76,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "red_rose_beauty_room",
    "businessName": "Red Rose Beauty Room",
    "categoryPrimary": "lashes",
    "categorySecondary": "beauty_studio",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "red_rose_beauty_room",
    "instagramUrl": "https://www.instagram.com/red_rose_beauty_room/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Online booking mentioned in snippet",
    "fitScore": 80,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "riga.lashes.academy",
    "businessName": "Riga Lashes Academy",
    "categoryPrimary": "lashes",
    "categorySecondary": "brows",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "riga.lashes.academy",
    "instagramUrl": "https://www.instagram.com/riga.lashes.academy/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Service-led lash/brow account",
    "fitScore": 74,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "siaadnails",
    "businessName": "A&D Nails",
    "categoryPrimary": "nails",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "siaadnails",
    "instagramUrl": "https://www.instagram.com/siaadnails/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "browser",
    "leadSourceSecondary": "google_search",
    "complianceNotes": "Riga nail salon with public addresses",
    "fitScore": 74,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "artnails_riga",
    "businessName": "Art Nails Riga",
    "categoryPrimary": "nails",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "artnails_riga",
    "instagramUrl": "https://www.instagram.com/artnails_riga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37120122289",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "Google live result snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "budget",
    "audienceSignal": "local_consumer",
    "languageSignal": "en",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "browser",
    "leadSourceSecondary": "google_search",
    "complianceNotes": "Address and public phone visible in snippet",
    "fitScore": 82,
    "confidenceScore": "high",
    "qaStatus": "approved"
  },
  {
    "id": "houseofnailsriga",
    "businessName": "House of Nails Riga",
    "categoryPrimary": "nails",
    "categorySecondary": "pedicure",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "houseofnailsriga",
    "instagramUrl": "https://www.instagram.com/houseofnailsriga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37124112662 / +37128555414",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "Google live result snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "mid",
    "audienceSignal": "local_consumer",
    "languageSignal": "en",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "browser",
    "leadSourceSecondary": "google_search",
    "complianceNotes": "Two branches and booking CTA",
    "fitScore": null,
    "confidenceScore": "76",
    "qaStatus": "medium"
  },
  {
    "id": "miami.beauty.salon",
    "businessName": "Miami Beauty Salon",
    "categoryPrimary": "nails",
    "categorySecondary": "brows",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "miami.beauty.salon",
    "instagramUrl": "https://www.instagram.com/miami.beauty.salon/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "mixed",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Booking online noted in snippet",
    "fitScore": 79,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "nailidriga",
    "businessName": "NAIL ID Riga",
    "categoryPrimary": "nails",
    "categorySecondary": "pedicure",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "nailidriga",
    "instagramUrl": "https://www.instagram.com/nailidriga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37122334758",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "mid",
    "audienceSignal": "local_consumer",
    "languageSignal": "mixed",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business phone visible in search snippet",
    "fitScore": 78,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "nailinfinity_studio",
    "businessName": "Nailinfinity Studio",
    "categoryPrimary": "nails",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "nailinfinity_studio",
    "instagramUrl": "https://www.instagram.com/nailinfinity_studio/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business profile found",
    "fitScore": 62,
    "confidenceScore": "low",
    "qaStatus": "needs_review"
  },
  {
    "id": "one.beauty.nails",
    "businessName": "One Beauty Nails",
    "categoryPrimary": "nails",
    "categorySecondary": "pedicure",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "one.beauty.nails",
    "instagramUrl": "https://www.instagram.com/one.beauty.nails/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37128857000",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "mid",
    "audienceSignal": "local_consumer",
    "languageSignal": "mixed",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business phone visible in snippet",
    "fitScore": 84,
    "confidenceScore": "high",
    "qaStatus": "approved"
  },
  {
    "id": "pinkyswear_studio",
    "businessName": "Pinky Swear Studio",
    "categoryPrimary": "nails",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "pinkyswear_studio",
    "instagramUrl": "https://www.instagram.com/pinkyswear_studio/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "explicit",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "en",
    "languageSignal": "",
    "lastActivityDatePublic": "active",
    "activeStatus": "browser",
    "leadSourcePrimary": "google_search",
    "leadSourceSecondary": "Private nail artist wording",
    "complianceNotes": "owner-led",
    "fitScore": 72,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  },
  {
    "id": "riganails",
    "businessName": "Riga Nails",
    "categoryPrimary": "nails",
    "categorySecondary": "brows",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "riganails",
    "instagramUrl": "https://www.instagram.com/riganails/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "+37126922200",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "strong_inferred",
    "ownerSignalSource": "Instagram snippet",
    "microbusinessSignal": "small_studio",
    "priceLevelSignal": "mid",
    "audienceSignal": "local_consumer",
    "languageSignal": "mixed",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business phone visible in snippet",
    "fitScore": 84,
    "confidenceScore": "high",
    "qaStatus": "approved"
  },
  {
    "id": "stoptimenailriga",
    "businessName": "Stop Time Nail Riga",
    "categoryPrimary": "nails",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "stoptimenailriga",
    "instagramUrl": "https://www.instagram.com/stoptimenailriga/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business profile found",
    "fitScore": 62,
    "confidenceScore": "low",
    "qaStatus": "needs_review"
  },
  {
    "id": "studio44_lv",
    "businessName": "Studio 44",
    "categoryPrimary": "nails",
    "categorySecondary": "",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "studio44_lv",
    "instagramUrl": "https://www.instagram.com/studio44_lv/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "weak_inferred",
    "ownerSignalSource": "small_studio",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "unknown",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "web_search",
    "leadSourceSecondary": "instagram",
    "complianceNotes": "Public business profile found",
    "fitScore": 60,
    "confidenceScore": "low",
    "qaStatus": "needs_review"
  },
  {
    "id": "verushanails",
    "businessName": "Verusha Nails",
    "categoryPrimary": "nails",
    "categorySecondary": "pedicure",
    "city": "Riga",
    "country": "Latvia",
    "instagramHandle": "verushanails",
    "instagramUrl": "https://www.instagram.com/verushanails/",
    "websiteUrl": "",
    "googleMapsUrl": "",
    "bookingUrl": "",
    "facebookUrl": "",
    "tiktokUrl": "",
    "publicPhone": "",
    "publicEmail": "",
    "ownerNamePublic": "",
    "femaleOwnerSignal": "explicit",
    "ownerSignalSource": "solo",
    "microbusinessSignal": "mid",
    "priceLevelSignal": "local_consumer",
    "audienceSignal": "en",
    "languageSignal": "",
    "lastActivityDatePublic": "",
    "activeStatus": "active",
    "leadSourcePrimary": "browser",
    "leadSourceSecondary": "google_search",
    "complianceNotes": "Latvia Riga manicure/pedicure master with DM CTA",
    "fitScore": 80,
    "confidenceScore": "medium",
    "qaStatus": "approved"
  }
];
